### ISSUE TITLE
Simonw's llm cli: Template usage.

### ISSUE THREAD

**Issue by irthomasthomas** [irthomasthomas/undecidability#62]
Here are the code blocks extracted from the readme file:

```bash
llm 'Summarize this: $input' --save summarize
```

```bash 
llm --system 'Summarize this' --save summarize
```

```bash
llm --system 'Summarize this' --model gpt-4 --save summarize
```

```bash
llm --system 'Summarize this text in the voice of $voice' \
  --model gpt-4 -p voice GlaDOS --save summarize
```

```bash
curl -s https://example.com/ | llm -t summarize
```

```bash
curl -s https://llm.datasette.io/en/latest/ | \
  llm -t summarize -m gpt-3.5-turbo-16k
```

```bash
llm templates
```

```bash
llm templates edit summarize
```

```yaml
prompt: 'Summarize this: $input'
```

```yaml
prompt: >
    Summarize the following text.

    Insert frequent satirical steampunk-themed illustrative anecdotes.
    Really go wild with that.

    Text to summarize: $input
```

```bash
curl -s 'https://til.simonwillison.net/macos/imovie-slides-and-audio' | \
  strip-tags -m | llm -t steampunk -m 4
```

```yaml  
system: Summarize this
```

```yaml
system: You speak like an excitable Victorian adventurer  
prompt: 'Summarize this: $input'
```

```yaml
prompt: |
    Suggest a recipe using ingredients: $ingredients

    It should be based on cuisine from this country: $country
```

```bash
llm -t recipe -p ingredients 'sausages, milk' -p country Germany
```

```yaml
system: Summarize this text in the voice of $voice
```

```bash
curl -s 'https://til.simonwillison.net/macos/imovie-slides-and-audio' | \
  strip-tags -m | llm -t summarize -p voice GlaDOS 
```

```yaml
system: Summarize this text in the voice of $voice
defaults:
  voice: GlaDOS
```

```yaml
model: gpt-4
system: roast the user at every possible opportunity, be succinct
```

```bash
llm -t roast 'How are you today?'
```
